name: Cx1 Scan
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkmarx AST Github Action
      # You may pin to the exact commit or the version.
      # uses: Checkmarx/ast-github-action@3bbaca0807ff5abd587965391138479c23b7b369
      uses: Checkmarx/ast-github-action@main
      with:
        # Provide the AST portal URL
        base_uri: https://deu.ast.checkmarx.net
        # Provide the Tenant for AST portal URL
        cx_tenant: cx_tam_appsec_michael_kubiaczyk
        # Client ID for AST portal authentication
        cx_client_id: ${{ secrets.CX1_CLIENT_ID }}
        # Secret key for AST portal authentication
        cx_client_secret: ${{ secrets.CX1_CLIENT_SECRET }}
        # Select a Checkmarx Project Name
        project_name: ssba-ghaction
        # Branch name
        branch: ${{ github.head_ref || github.ref }}
        # GitHub API Token
        github_token: ${{ github.token }}
        # Additional parameters for AST scan
        additional_params: "--debug --report-format sarif --output-path . --scan-types sast --sast-preset-name \"All\" "
        # Repository name for PR decoration
        repo_name: ${{ github.event.repository.name }}
        # Organization name to create the Pr comment
        namespace: ${{ github.repository_owner }}
        # Pr Number of the pull request that needs the decoration
        pr_number: ${{ github.event.number }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: cx_result.sarif
